import { useState } from "react";
import { Link } from "react-router";
import {
  FileText,
  Download,
  Calendar,
  ArrowRight,
  Filter,
  Search,
} from "lucide-react";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Input } from "../components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../components/ui/select";

export function Resources() {
  return (
    <div>
      <HeroSection />
      <ResourcesListSection />
      <NewsSection />
      <CTASection />
    </div>
  );
}

function HeroSection() {
  return (
    <section className="relative bg-gradient-to-br from-[var(--brand-navy-dark)] to-[var(--brand-navy)] text-white py-20 lg:py-32">
      <div className="absolute inset-0 opacity-10">
        <div className="absolute bottom-0 right-0 w-96 h-96 bg-[var(--brand-lime)] rounded-full blur-3xl" />
      </div>

      <div className="relative container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto text-center">
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold mb-6 text-white">
            Resources & Updates
          </h1>
          <p className="text-lg lg:text-xl text-white/90 leading-relaxed">
            Policy briefs, press releases, research, and updates on Louisiana
            hemp beverage advocacy
          </p>
        </div>
      </div>
    </section>
  );
}

function ResourcesListSection() {
  const [searchTerm, setSearchTerm] = useState("");
  const [filterCategory, setFilterCategory] = useState("all");

  const resources = [
    {
      title: "Louisiana's Regulatory Framework: A Model for Federal Policy",
      description:
        "Comprehensive overview of Louisiana's hemp beverage regulations, including testing requirements, age restrictions, and licensing.",
      category: "Policy Brief",
      date: "March 10, 2026",
      type: "PDF",
      featured: true,
    },
    {
      title: "Federal Ban Timeline & Economic Impact Analysis",
      description:
        "Analysis of the November 2026 federal ban and projected impact on Louisiana jobs, tax revenue, and businesses.",
      category: "Analysis",
      date: "March 5, 2026",
      type: "PDF",
      featured: true,
    },
    {
      title: "Coalition Launches to Advocate for Smart Hemp Policy",
      description:
        "Official announcement of the Louisiana Hemp Beverage Coalition and our mission to protect the state's regulated industry.",
      category: "Press Release",
      date: "February 20, 2026",
      type: "PDF",
      featured: false,
    },
    {
      title: "Talking Points: Engaging State & Federal Lawmakers",
      description:
        "Key messages and data points for coalition members and supporters to use when contacting representatives.",
      category: "Advocacy Tool",
      date: "February 15, 2026",
      type: "PDF",
      featured: false,
    },
    {
      title: "Third-Party Testing Standards in Louisiana",
      description:
        "Technical breakdown of Louisiana's mandatory testing requirements for hemp beverages and how they protect consumers.",
      category: "Research",
      date: "February 8, 2026",
      type: "PDF",
      featured: false,
    },
    {
      title: "Age Verification & Retail Compliance Best Practices",
      description:
        "Guide for retailers on implementing age restrictions and point-of-sale verification for hemp beverages.",
      category: "Industry Guide",
      date: "January 28, 2026",
      type: "PDF",
      featured: false,
    },
    {
      title: "Statement on Federal Funding Bill Hemp Provision",
      description:
        "Coalition response to the federal ban announcement and our commitment to working with lawmakers on sensible alternatives.",
      category: "Press Release",
      date: "January 15, 2026",
      type: "PDF",
      featured: false,
    },
    {
      title: "Hemp Beverage Industry Economic Impact Report",
      description:
        "Data on jobs, tax revenue, and economic activity generated by Louisiana's regulated hemp beverage industry.",
      category: "Research",
      date: "January 10, 2026",
      type: "PDF",
      featured: false,
    },
  ];

  const filteredResources = resources.filter((resource) => {
    const matchesSearch =
      resource.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      resource.description.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCategory =
      filterCategory === "all" || resource.category === filterCategory;
    return matchesSearch && matchesCategory;
  });

  const categories = [
    "all",
    "Policy Brief",
    "Press Release",
    "Analysis",
    "Advocacy Tool",
    "Research",
    "Industry Guide",
  ];

  return (
    <section className="py-16 lg:py-24 bg-white">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-6xl mx-auto">
          {/* Filters */}
          <div className="mb-12">
            <div className="flex flex-col sm:flex-row gap-4">
              <div className="flex-1 relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-[var(--neutral-400)]" />
                <Input
                  type="text"
                  placeholder="Search resources..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-10"
                />
              </div>
              <div className="sm:w-64">
                <Select value={filterCategory} onValueChange={setFilterCategory}>
                  <SelectTrigger>
                    <Filter className="w-4 h-4 mr-2" />
                    <SelectValue placeholder="Filter by category" />
                  </SelectTrigger>
                  <SelectContent>
                    {categories.map((category) => (
                      <SelectItem key={category} value={category}>
                        {category === "all" ? "All Categories" : category}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
          </div>

          {/* Featured Resources */}
          {filterCategory === "all" && !searchTerm && (
            <div className="mb-12">
              <h2 className="text-2xl font-bold mb-6 text-[var(--neutral-900)]">
                Featured Resources
              </h2>
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {resources
                  .filter((r) => r.featured)
                  .map((resource, index) => (
                    <Card
                      key={index}
                      className="border-l-4 border-l-[var(--brand-teal-dark)] hover:shadow-lg transition-shadow"
                    >
                      <CardHeader>
                        <div className="flex items-center gap-2 mb-2">
                          <span className="text-xs font-semibold px-2 py-1 bg-[var(--brand-teal-dark)]/10 text-[var(--brand-teal-dark)] rounded">
                            {resource.category}
                          </span>
                          <span className="text-xs text-[var(--neutral-500)]">
                            {resource.date}
                          </span>
                        </div>
                        <CardTitle className="text-xl text-[var(--neutral-900)]">
                          {resource.title}
                        </CardTitle>
                      </CardHeader>
                      <CardContent>
                        <p className="text-[var(--neutral-600)] mb-4">
                          {resource.description}
                        </p>
                        <Button
                          variant="outline"
                          size="sm"
                          className="border-[var(--brand-teal-dark)] text-[var(--brand-teal-dark)] hover:bg-[var(--brand-teal-dark)] hover:text-white"
                        >
                          <Download className="w-4 h-4 mr-2" />
                          Download {resource.type}
                        </Button>
                      </CardContent>
                    </Card>
                  ))}
              </div>
            </div>
          )}

          {/* All Resources */}
          <div>
            <h2 className="text-2xl font-bold mb-6 text-[var(--neutral-900)]">
              {filterCategory === "all" && !searchTerm
                ? "All Resources"
                : `${filteredResources.length} Result${
                    filteredResources.length !== 1 ? "s" : ""
                  }`}
            </h2>

            {filteredResources.length === 0 ? (
              <Card className="border-2 border-dashed border-[var(--neutral-300)]">
                <CardContent className="p-12 text-center">
                  <FileText className="w-12 h-12 text-[var(--neutral-400)] mx-auto mb-4" />
                  <p className="text-lg text-[var(--neutral-600)]">
                    No resources found matching your criteria.
                  </p>
                </CardContent>
              </Card>
            ) : (
              <div className="space-y-4">
                {filteredResources.map((resource, index) => (
                  <Card
                    key={index}
                    className="border-2 border-[var(--neutral-200)] hover:border-[var(--brand-teal-dark)] hover:shadow-md transition-all"
                  >
                    <CardContent className="p-6">
                      <div className="flex items-start justify-between gap-4">
                        <div className="flex items-start gap-4 flex-1">
                          <div className="w-12 h-12 bg-[var(--brand-teal-dark)]/10 rounded-lg flex items-center justify-center flex-shrink-0">
                            <FileText className="w-6 h-6 text-[var(--brand-teal-dark)]" />
                          </div>
                          <div className="flex-1">
                            <div className="flex items-center gap-2 mb-2">
                              <span className="text-xs font-semibold px-2 py-1 bg-[var(--neutral-100)] text-[var(--neutral-700)] rounded">
                                {resource.category}
                              </span>
                              <span className="text-xs text-[var(--neutral-500)]">
                                {resource.date}
                              </span>
                            </div>
                            <h3 className="font-semibold text-lg text-[var(--neutral-900)] mb-2">
                              {resource.title}
                            </h3>
                            <p className="text-sm text-[var(--neutral-600)]">
                              {resource.description}
                            </p>
                          </div>
                        </div>
                        <Button
                          variant="outline"
                          size="sm"
                          className="border-[var(--brand-teal-dark)] text-[var(--brand-teal-dark)] hover:bg-[var(--brand-teal-dark)] hover:text-white flex-shrink-0"
                        >
                          <Download className="w-4 h-4 mr-2" />
                          Download
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}

function NewsSection() {
  const newsItems = [
    {
      title: "Coalition Meets with Louisiana Congressional Delegation",
      excerpt:
        "Members presented Louisiana's regulatory framework to federal lawmakers in Washington, D.C.",
      date: "March 8, 2026",
      category: "Coalition News",
    },
    {
      title: "New Members Join Coalition from Retail Sector",
      excerpt:
        "Three major Louisiana grocery chains sign on to support smart hemp beverage policy.",
      date: "February 28, 2026",
      category: "Membership",
    },
    {
      title: "Coalition Testimony Before State Commerce Committee",
      excerpt:
        "Executive director presents data on Louisiana's hemp beverage market and regulatory success.",
      date: "February 12, 2026",
      category: "Advocacy",
    },
  ];

  return (
    <section className="py-16 lg:py-24 bg-[var(--neutral-50)]">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl lg:text-4xl font-bold mb-4 text-[var(--neutral-900)]">
              Latest News & Updates
            </h2>
            <p className="text-lg text-[var(--neutral-600)]">
              Recent coalition activities and advocacy wins
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {newsItems.map((item, index) => (
              <Card
                key={index}
                className="border-2 border-[var(--neutral-200)] hover:border-[var(--brand-teal-dark)] hover:shadow-lg transition-all"
              >
                <CardHeader>
                  <div className="flex items-center gap-2 mb-2">
                    <span className="text-xs font-semibold px-2 py-1 bg-[var(--brand-green-dark)]/10 text-[var(--brand-green-dark)] rounded">
                      {item.category}
                    </span>
                  </div>
                  <CardTitle className="text-lg text-[var(--neutral-900)]">
                    {item.title}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-[var(--neutral-600)] mb-4">
                    {item.excerpt}
                  </p>
                  <div className="flex items-center gap-2 text-xs text-[var(--neutral-500)]">
                    <Calendar className="w-4 h-4" />
                    <span>{item.date}</span>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          <div className="text-center mt-8">
            <Button asChild variant="outline">
              <Link to="/contact">
                Subscribe to Updates <ArrowRight className="ml-2 w-5 h-5" />
              </Link>
            </Button>
          </div>
        </div>
      </div>
    </section>
  );
}

function CTASection() {
  return (
    <section className="py-16 lg:py-24 bg-gradient-to-br from-[var(--brand-navy-dark)] to-[var(--brand-navy)] text-white">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl lg:text-4xl font-bold mb-4 text-white">
            Members Get Access to More
          </h2>
          <p className="text-lg text-white/90 mb-8">
            Coalition members receive exclusive research, talking points, and
            advocacy materials not available to the public.
          </p>
          <Button
            asChild
            size="lg"
            className="bg-[var(--brand-teal-dark)] hover:bg-[var(--brand-teal)] text-white px-8"
          >
            <Link to="/get-involved">
              Join the Coalition <ArrowRight className="ml-2 w-5 h-5" />
            </Link>
          </Button>
        </div>
      </div>
    </section>
  );
}
